week4/w4d4/Music_app/config/routes.rb
MusicApp::Application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :albums
  resources :tracks
end

week4/w4d4/Music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  album_type :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#  band_id    :integer
#

class Album < ActiveRecord::Base
  validates :name, :album_type, :band_id, presence: true

  belongs_to(
    :band,
    class_name: 'Band',
    foreign_key: :band_id,
    primary_key: :id
  )

  has_many(
    :tracks,
    class_name: 'Track',
    foreign_key: :album_id,
    primary_key: :id
  )

  ALBUM_TYPES = [
    "live",
    "studio"
  ]
end

week4/w4d4/Music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many(
    :albums,
    class_name: 'Album',
    foreign_key: :band_id,
    primary_key: :id
  )

  has_many(
    :tracks,
    through: :albums,
    source: :tracks
  )

end

week4/w4d4/Music_app/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  track_name :string(255)      not null
#  album_id   :integer          not null
#  track_type :string(255)      not null
#  lyrics     :text
#  created_at :datetime
#  updated_at :datetime
#

class Track < ActiveRecord::Base
  validates :track_name, :track_type, :album_id, presence: true

  belongs_to(
    :album,
    class_name: 'Album',
    foreign_key: :album_id,
    primary_key: :id
  )

  has_one(
    :band,
    through: :album,
    source: :band
  )

  TRACK_TYPES = [
    "bonus",
    "regular"
  ]
end

week4/w4d4/Music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  validate :email, :password_digest, :session_token, presence: true
  validate :email, uniqueness: true
  after_initialize :ensure_session_token


  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil if user.nil?
    if user.is_password?(password)
      user
    else
      nil
    end
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

week4/w4d4/Music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @album = Album.new
    @bands = Band.all
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      render json: @album.errors.full_message
    end
  end

  def show
    @album = Album.find(params[:id])
    @band = Band.find(@album.band_id)
    render :show
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      render :edit
    end
  end

  def index
    @albums = Album.all
    render :index
  end

  def edit
    @album = Album.find(params[:id])
    @bands = Band.all
    render :edit
  end

  def destroy
    @album = Album.find(params[:id])

    if @album.destroy
      redirect_to new_album_url
    else
      render :show
    end 
  end

  private

  def album_params
    params.require(:album).permit(:name, :album_type, :band_id)
  end
end

week4/w4d4/Music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out!(user)
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

week4/w4d4/Music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
    @albums = @band.albums
    render :show
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      render :edit
    end
  end
  #
  def index
    @bands = Band.all
    render :index
  end

  def destroy
    @band = Band.find(params[:id])

    @band.destroy unless @band.nil?
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

week4/w4d4/Music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password])

    if user.nil?

      render json: 'this is not a valid user'
    else
      log_in_user!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    log_out!(current_user)
    redirect_to new_session_url
  end
end

week4/w4d4/Music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    @track = Track.new
    @albums = Album.all
    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      @albums = Album.all
      render  :new
    end
  end

  def update
    @track = Track.find(params[id])

    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      render :edit
    end
  end

  def index
    @tracks = Tracks.all
  end

  def show
    @track = Track.find(params[:id])
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def destroy
    @track = track.find(params[:id])
    if @track.destroy
      redirect_to new_tracks_url
    else
      render :show
    end
  end

  private

  def track_params
    params.require(:track).permit(:track_name, :album_id, :track_type, :lyrics)
  end
end

week4/w4d4/Music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      render jason: @user.errors.full_messages
    end

  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

week4/w4d4/Music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

week4/w4d4/Music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

week4/w4d4/Music_app/app/helpers/bands_helper.rb
module BandsHelper
end

week4/w4d4/Music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

week4/w4d4/Music_app/app/helpers/tracks_helper.rb
module TracksHelper
end

week4/w4d4/Music_app/app/helpers/users_helper.rb
module UsersHelper
end

week4/w4d4/Music_app/app/views/albums/edit.html.erb
<h1> Update an Album </h1>

<form action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="album_name">Name</label>
    <input
      type="text"
      name="album[name]"
      id="album_name"
      value="<%= @album.name %>">

  <br>
  <label for="album_type">Album type</label>
  <br>
      <% Album::ALBUM_TYPES.each do |typpe| %>
        <input type="radio"
                name="album[album_type]"
                value="<%= typpe %>"
                <%= "checked" if @album.album_type == typpe %>>
                <%= typpe %><br>
      <% end %>
  <br>

  <label for="band_name">Choose a Band</label>
  <select name="album[band_id]"
          id="band_name">
    <option></option>
    <% @bands.each do |band| %>
      <% selected = @album.band_id == band.id %>>
      <option <%= selected ? "selected" : "" %>
              value="<%= band.id %>">
        <%= band.name %>
    </option>
    <% end %>
  </selected>


  <br>
  <br>
  <p><%= albums_url %></p>
  <input type="submit">
</form>

week4/w4d4/Music_app/app/views/albums/index.html.erb
<h1> All Albums </h1>
<ul>
  <% @albums.each do |album| %>
  <li><%= link_to album.name, album_url(album) %></li>
  <% end %>
</ul>

week4/w4d4/Music_app/app/views/albums/new.html.erb
<h1> Create a new Album </h1>

<form action="<%= albums_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="album_name">Name</label>
    <input
      type="text"
      name="album[name]"
      id="album_name">

  <br>
  <label for="album_type">Album type</label>
  <br>
      <% Album::ALBUM_TYPES.each do |typpe| %>
        <input type="radio"
                name="album[album_type]"
                value="<%= typpe %>"
                <%= "checked" if @album.album_type == typpe %>>
                <%= typpe %><br>
      <% end %>
  <br>

  <label for="band_name">Choose a Band</label>
  <select name="album[band_id]"
          id="band_name">
    <option></option>
    <% @bands.each do |band| %>
      <% selected = @album.band_id == band.id %>>
      <option <%= selected ? "selected" : "" %>
              value="<%= band.id %>">
        <%= band.name %>
    </option>
    <% end %>
  </selected>


  <br>
  <br>
  <p><%= albums_url %></p>
  <input type="submit">
</form>

week4/w4d4/Music_app/app/views/albums/show.html.erb
<h1> Album's name is <%= @album.name %> </h2>

  <ul>
    <li>Album's name: <%= @album.name %></li>
    <li>Album's type: <%= @album.album_type %></li>
    <li>Album's band id: <%= @album.band_id %></li>
  </ul>

  <br>
  <p><%= link_to "Go to Band's Page(#{@band.name})", band_url(@band) %></p>
  <br>
  <br>

  <p><%= link_to "Edit #{@album.name}", edit_album_url(@album) %></p>
  <p><%= link_to "Destroy #{@album.name}", album_url(@album), method: :delete %></p>

  <p><%= link_to "Create a new Album", new_album_url %></p>

week4/w4d4/Music_app/app/views/bands/edit.html.erb
<h1> Edit this Band </h1>

<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="band_name">Name</label>
  <input type="text"
  name="band[name]"
  id="band_name">

  <br>
  <input type = "submit">

</form>

week4/w4d4/Music_app/app/views/bands/index.html.erb
<h1> Our Created Bands </h1>
<ul>
<% @bands.each do |band| %>
  <li><%= link_to band.name, band_url(band) %></li>
<% end %>
</ul>

week4/w4d4/Music_app/app/views/bands/new.html.erb
<h1> Create a New Band </h1>

<form action= "<%= bands_url %>" method="post">
  <input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <label for="band_name">Name</label>
  <input type="text"
  name="band[name]"
  id="band_name">

  <br>
  <input type = "submit">

</form>

week4/w4d4/Music_app/app/views/bands/show.html.erb
<h1> Band's name is <%= @band.name %> </h2>

<p><%= link_to "Edit #{@band.name}", edit_band_url(@band) %></p>
<p><%= link_to "Destroy #{@band.name}", band_url(@band), method: :delete %></p>

<p><%= link_to "Create a new Band", new_band_url %></p>


<h3> Here are link's to <%= @band.name %>'s albums </h3>
<ul>
  <% @albums.each do |album| %>
  <li><%= link_to album.name, album_url(album) %></li>
  <% end %>
</ul>

week4/w4d4/Music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<% if current_user.nil? %>
<%= link_to "Sign in", new_session_url %> or
<%= link_to "Sign up", new_user_url %>
<% else %>
<%= current_user.email %>
<%= button_to "Logout", session_url, method: :delete %>
<% end %>

</body>
</html>

week4/w4d4/Music_app/app/views/tracks/new.html.erb
<h1> Create a new Track</h1>

<form action="<%= tracks_url %>" method="post">
    <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <label for="track_name">Name</label>
    <input
    type="text"
    name="track[track_name]"
    id="track_name">

  <label for="track_album_id">Choose an Album</label>
  <select name="track[album_id]"
    id="track_album_id">
    <option></option>
      <% @albums.each do |album| %>
        <% selected = @track.album_id == album.id %>>
        <option <%= selected ? "selected" : "" %>
            value="<%= album.id %>">
            <%= album.name %>
        </option>
      <% end %>
  </selected>
<br>
<br>

<br>
  <label for="track_type">Track type</label>
    <br>
    <% Track::TRACK_TYPES.each do |track| %>
      <input type="radio"
        name="track[track_type]"
        value="<%= track %>"
        <%= "checked" if @track.track_type == track %>>
        <%= track %><br>
  <% end %>
<br>

<br>
<input type="submit">
</form>

week4/w4d4/Music_app/app/views/tracks/show.html.erb
<h1> Track's name is <%= @track.track_name %> </h2>

week4/w4d4/Music_app/app/views/users/new.html.erb
<h1> Sign Up </h1>

<form action= "<%= users_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="user_email">Email</label>
  <input type="text"
          name="user[email]"
          id="user_email">

  <br>
  <br>

  <label for="user_password">Password</label>
  <input type="password"
          name="user[password]"
          id="user_password">

  <br>

  <input type = "submit">

</form>

week4/w4d4/Music_app/app/views/users/show.html.erb
<h1> Hello <%= @user.email %> <h1>